### ISSUE TITLE
How do you use this library?

### ISSUE THREAD

**Issue by arc95** [NLog/NLog.Elmah#14]
Hi. Love this library. But beyond the name, I have not a clue how to use it in my project. Does this take calls to NLog and send them to ELMAH? How do you use it? Just a few sentences would help me tremendously. 

I have an ASP.NET MVC app that has NLog and I'd like to add ELMAH, so that all existing NLog calls get sent to ELMAH. Thanks.

**Comment by 304NotModified** [comment]
Just install the nuget package and use the target Elmah

I will write a better how to soon :)

**Comment by arc95** [comment]
Thanks, @304NotModified. A follow-up: I've installed the package and added the attribute,

```c#
[Target("Elmah")]
public class HomeController : Controller
{
	private static Logger _logger = LogManager.GetCurrentClassLogger();
	public ActionResult Index()
	{
		LogEventInfo logEvent = new LogEventInfo(LogLevel.Info, _logger.Name, "Some error by alex");
		_logger.Log(logEvent);
		return View();
	}

	public ActionResult About()
	{
		return View();
	}

	public ActionResult Contact()
	{
		ViewBag.Message = "Your contact page.";

		return View();
	}
}
```
But it's not writing to Elmah, though it is writing to NLog when I go to `Index`. I have the Elmah.MVC package installed, so I can go to `/Elmah` and see the errors.

**Comment by 304NotModified** [comment]
You need to create an NLog config. That could by a XML (nlog.config) file or C#, please read

https://github.com/NLog/NLog/wiki/Tutorial

the target in this case is Elmah, so somthing like this

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target name="target1" xsi:type="Elmah" />
    </targets>

    <rules>
        <logger name="*" minlevel="Info" writeTo="target1" />
    </rules>
</nlog>

```

**Comment by 304NotModified** [comment]
updated: https://github.com/NLog/NLog.Elmah#usage

**Comment by arc95** [comment]
Thanks, @304NotModified! Very nice instructions! 

That fixed it. Also, users can [safely ignore the warning](https://stackoverflow.com/a/39311279/177416) it throws for that custom target:

`This is an invalid xsi:type 'http://www.nlog-project.org/schemas/NLog.xsd:Elmah'`

**Comment by 304NotModified** [comment]
good point, thanks!

**Comment by arc95** [comment]
Answered my question on this using your library: https://stackoverflow.com/a/44974578/177416

**Update**: Fixed the xml not showing up in SO answer.
