### ISSUE TITLE
Build fails due to licenseUrl and PackageIcon

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Elmah#35]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\projects\nlog\NLog.Elmah\NLog.Elmah.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at

**Comment by 304NotModified** [comment]
See same fix here: https://github.com/NLog/NLog.Extensions.Logging/pull/461

**Comment by snakefoot** [comment]
Resolved by #36
