### ISSUE TITLE
Can't set Elmah Source.

### ISSUE THREAD

**Issue by jmo21** [NLog/NLog.Elmah#7]
Per title, I'd like to be able to have the source written to the Elmah table. At the moment, when using this very handy utility, the source column is blank.

I know Elmah uses ApplicationName in it's settings, but Source is useful for defining different sub systems of a larger app.

(apologies if there is a way to do this, but I can't see it in the docs!)

**Comment by 304NotModified** [comment]
Hi,

Proposal : add `ApplicationName` property to the Elmah Target. You can configure it with `${callsite}`

**Comment by 304NotModified** [comment]
Proposal updated. Let me know if that will fix your issue.

**Comment by jmo21** [comment]
Sounds good!

**Comment by jmo21** [comment]
Actually, I am hoping to update the Source column, not the ApplicationName.

ApplicationName is set in the Elmah config itself. THANKS!

So maybe Source="${callsite}"

**Comment by 304NotModified** [comment]
OK, I can try something this week. 

You can also try it yourself, it's really simple to add:

file to be changed: https://github.com/NLog/NLog.Elmah/blob/master/NLog.Elmah/ElmahTarget.cs
helping blog post: http://nlog-project.org/2015/06/30/extending-nlog-is-easy.html

and if you need some help on it, we can give support of course. 

just let me know

**Comment by 304NotModified** [comment]
@jmo21 can you give me some feedback on the proposal?

**Comment by jmo21** [comment]
I'll try and pick it up at some point, I'm in the middle of a release crunch at the moment. thanks again!

**Comment by 304NotModified** [comment]
Is this still needed?
